### ISSUE TITLE
[BUG] Roadmap links do not work (at least for users who are not members)

### ISSUE THREAD

**Issue by billdenney** [pharmaverse/pharmaverse#117]
**Describe the bug**
The links in this section of the readme go to 404 pages: https://github.com/pharmaverse/pharmaverse#roadmap

**Additional context**
If the links work for pharmaverse members, perhaps confirm in a incognito browser to emulate people who are not members.

**Comment by rossfarrugia** [comment]
@billdenney can you double check again please? this should be open to all. the #roadmap bit of the link just takes you to the roadmap section of the readme like below:
![image](https://user-images.githubusercontent.com/82581364/160166411-ec69f3cb-5894-4999-8e24-b99f5c12524a.png)

so if you have access to the readme itself this should work. let me know if you can't see the readme at all though?

i should say its more of a roadmap of our website actions rather than the pharmaverse as a whole. we don't have a roadmap as such, but if you're interested in specific packages then the dev teams for them could share planned priorities, e.g. for {admiral} we're looking next at ADLB and ADRS/ADTTE (via {admiralonco}) as an example. let me know if any specific info needed and i could help connect.

**Comment by billdenney** [comment]
I was unclear in my initial comment.  I was meaning that the links in https://github.com/orgs/pharmaverse/projects/3/views/9 and https://github.com/orgs/pharmaverse/projects/3/views/1?layout=board don't work for me.

If those are related to the roadmap for the website, you're right that was not the roadmap that I was looking for.  My thought was along the lines of a roadmap of the parts of the end-to-end data path that are supported and considered within scope for pharmaverse.  My thoughts go to something like:

* Raw data
    * List of packages supporting conversion from raw to SDTM
* SDTM
    * List of packages supporting conversion from SDTM to ADaM
* ADaM
    * List of packages supporting conversion from ADaM to TLF
* TLF

And, for each of those lists of packages, indicate some degree of completeness and feature-richness (e.g. PackageX supports creation of ADSL and is considered feature complete for the initial release; PackageY supports conversion to SDTM DM domain with the minimal required columns).

**Comment by rossfarrugia** [comment]
yes, this repo is dedicated to the website, so i wouldn't worry about accessing those project boards for your need. 

what you request is something we're currently working on with our e2e vignettes for the pharmaverse site. our first one will be ADaM (basic ADSL example and then maybe a more complex one such as ADLB). then we plan to do similar for SDTM and TLF. i'd also add eSub to your proposed list, and under TLF we'll also cover interactive displays. maybe even PK too as discussed in email.

the timing is not so easy to estimate yet as certain packages are still closed-collaborations pending cross-company legal agreements. high level though we're hoping to have ADaM ready for the PHUSE US connect in May, and then the others will follow. some major packages for SDTM and TLF are only likely to open source later in the year. it's all very much a work in progress.

will close this issue, but don't hesitate to reach out for any more details needed.
