### ISSUE TITLE
FAQ: how does a package get added to pharmaverse?

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#126]
Add an faq to site on "how does a package get added to pharmaverse?" linking to our criteria on how we pick _(currently work in progress from council)_, explaining it is optional to be under our github org, and mentioning our badge of honour

**Comment by rossfarrugia** [comment]
Including:
- updates to the WG lists (Data, TLG, Technology - includes any other package)
- minimum recommended criteria packages need to follow: https://pharmaverse.org/contribute/lead/ (@mstackhouse to add)
- also general instruction on trying to avoid new packages where you might be able to collaborate and add to an existing pharmaverse package

**Comment by rossfarrugia** [comment]
@mstackhouse i left you a placeholder to update at https://github.com/pharmaverse/pharmaverse/blob/126_adding_packages/content/contribute/lead/_index.en.md - let me know once updated.

**Comment by mstackhouse** [comment]
@rossfarrugia I added my content. Let me know what you think

**Comment by rossfarrugia** [comment]
thanks @mstackhouse - looks really good! i made some minor clean-ups to make it more readable for the website and i'm going to take a more detailed review next week and will share with a few reps here for an extra sanity check, and then will try and push this to the website by end of next week. One comment: i wonder if the style bit more should be moved down to the `For other best practices` line, as its more a recommendation than a minimum inclusion criteria?

@MichaelRimler would be good for you to sanity check this too and let us know any comments given you were involved in the earlier discussions on this: https://github.com/pharmaverse/pharmaverse/blob/126_adding_packages/content/contribute/lead/_index.en.md

**Comment by rossfarrugia** [comment]
@mstackhouse i shared this draft with some of the package leads on Roche side for review and the main feedback so far is around the CRAN requirement and the minimal CI being quite high bars. what do you think?

e.g. admiralci only covers the following for our ongoing development (but then CRAN checks cover more):

```
          - {os: ubuntu-latest, r: '4.0', repos: 'https://cran.microsoft.com/snapshot/2021-03-31/'}
          - {os: ubuntu-latest, r: '4.1', repos: 'https://cran.microsoft.com/snapshot/2022-03-10/'}
          - {os: ubuntu-20.04, r: 'release', repos: 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest'}
```

for CRAN acceptance, i think most packages will go for this anyway but not sure if we need to call it out as a minimum?

**Comment by mstackhouse** [comment]
This is why I wanted to differentiate some packages as "candidates", because there's nothing stopping you from using them from GitHub, but CRAN gives a sort of milestone for packages to reach and the CRAN checks themselves are rather reasonable. Plus, it makes the package much more accessible to the agency without overhead because reviewers can just install them from a source they're already using to get packages. If we just call every package "pharmaverse", I think it gets confusing for a lot of the industry who don't really understand the R world yet - and it let's us mark packages that are a bit more fleshed out as safe to use, whereas something like envsetup is still young and still needs more input to fill its space. So I think this helps set expectations more clearly.

For CI tests, I personally think that Windows is an absolute must because reviewers primarily use Windows workstations to use R environments. That was eye opening to me from R Consortium submissions work groups. So I think cross OS builds is a very reasonable expectation, particularly because if we want pharmaverse used by the wider population, there are still plenty of windows desktop users out there.

And for the CI requirements, in my opinion:
- It's all forward looking. So it sets a pace of maintenance for which we can expect packages to compatible. Remember metacore having dplyr 1.0.0 issues? That's the type of thing I'm trying to avoid - dependency version conflicts so we can start a pace by which pharmaverse can actually work as an ecosystem
- It intentionally gives a higher maintenance requirement for pharmaverse packages which holds pharmaverse packages to a higher bar

**Comment by mstackhouse** [comment]
And last note on the CRAN acceptance - I noted in there that CRAN may not always be the target location, but until we have a reliable replacement I think it's reasonable.

**Comment by rossfarrugia** [comment]
thanks - useful points! will take it back for some more internal discussion this week and will get back to you

**Comment by MichaelRimler** [comment]
@rossfarrugia @mstackhouse I will take a look.

**Comment by rossfarrugia** [comment]
@mstackhouse i spoke again with some of the package leads here and some of our CI experts and their recommendation was to soften the messaging slightly in following ways:
- take out the past 4 releases of R checks, as we only ever release to CRAN on the latest R version anyway and not archives. If some teams choose to do a few versions back like admiralci then it can be helpful to not introduce too many things that will only work on latest version, but they felt 4 versions is excessive and will scare people off when we call it "minimal inclusion criteria"
- for the checking different OS make this more a recommendation to be done pre-release only (i.e. not every single PR via a gh action) and some dev teams may even choose to leave that as part of CRAN checks anyway, e.g. https://cran.r-project.org/web/checks/check_results_admiral.html

what do you think?

**Comment by mstackhouse** [comment]
@rossfarrugia we can back off on the 4 pre-release. I would just be cautious that while many orgs are getting better at keeping everything current, these sort of compatibility issues creep up even with Roche's R 3.6 environment - where metacore had dplyr 1.0.0 requirements that weren't compatible. That's one of the factors that had encouraged me to try to include the requirement in the first place. 

For the OS checks I'm fine with it being pre-release. That's way too much CI/CD for like a merge to dev check.

**Comment by rossfarrugia** [comment]
@mstackhouse i had a go at updating in the commit above. feel free to correct anything though and i'll plan to put this live on the site early next week ahead of R/Pharma

**Comment by mstackhouse** [comment]
@rossfarrugia  I'm ok with your edits.

**Comment by rossfarrugia** [comment]
p.s. i merged this branch into develop now and i'm working on checking the updates there to see how they render on the website before pushing live. @MichaelRimler if you have any comments though do shout either here for now or via a new issue after this closes
