### ISSUE TITLE
Can we get rid of the `develop` branch?

### ISSUE THREAD

**Issue by cicdguy** [pharmaverse/pharmaverse#200]
**Describe your idea**
Wanna get rid of the `develop` branch altogether.

**Describe alternatives you've considered**
Let's just use the `main` branch for development and publishing.

**Additional context**
Looks like the `develop` branch has already been merged into `main` and is ~50+ commits behind main. Also the branch is unprotected.

**Comment by rossfarrugia** [comment]
It's useful because of https://github.com/pharmaverse/pharmaverse#development--git-flow and we want to have a review process before making changes live to the site. looks like the request here should be for us to merge latest main into develop to bring it back in sync (as some merges have gone straight to main from other feature branches). Do you think this test branch needs protection rules?

**Comment by rossfarrugia** [comment]
merged with main to bring develop back in line now
