### ISSUE TITLE
{Package Review}: xportr

### ISSUE THREAD

**Issue by elimillera** [pharmaverse/pharmaverse#203]
Here is my proposal for what the Package review could look like. Based off of the JOSS review process. https://github.com/openjournals/joss-reviews/issues

Package Author/Advocate: Eli Miller @elimillera
Repository: https://github.com/atorus-research/xportr

Current Version: v0.2.1

Reviewers: @elimillera, others
Review Status: Pre-review

For each packages:
Package Use Case:
Statement of Need:

For Each Review
Description of Automated Tests/Checks:
Description of Package Documentation:
Description of Functionality and Package Structure:
Overall review of package and fit in pharmaverse:

**Comment by epijim** [comment]
As a general note - is this a discussion on the review process, or actually xportr being reviewed?

If the topic is the process, I like it. because of the context of being in the pharmaverse, for: 

> Overall review of package and fit in pharmaverse

I wonder if we get more explicit there and have something like:

> Novel and duplicative functionality relative to the existing pharmaverse packages 
> Review summary

As the pharmaverse is a bottom up collaboration rather than designed top down like the tidyverse, it's fine to have overlap. But I think we should acknowledge when each new package comes in how it relates to the ones already there.

**Comment by epijim** [comment]
Maybe for the package review template, we could start a discussion - with the aim of updating this so all new packages are consistently reviewed: https://github.com/pharmaverse/pharmaverse/blob/main/.github/ISSUE_TEMPLATE/new_package.md

**Comment by rossfarrugia** [comment]
Bit of both @epijim! Agree on the improvements to the new package issue template - I'll put some of the suggestions above into a PR to improve that.

@elimillera on {xportr} review itself, I've been using it for sometime and happy it fulfills the inclusion criteria. My one bugbear is that more examples could be in the documentation showing step by step how it works like raised in https://github.com/atorus-research/xportr/issues/81 - I know you guys are forming a team to address these though via getting some wider contributions.

**Comment by rossfarrugia** [comment]
@elimillera @epijim - what do you think of the commit i made above?

**Comment by MichaelRimler** [comment]
**Description of Automated Tests/Checks:**
Test coverage seems low – is 69% good?

**Description of Package Documentation:**
Strange rendering in the xportr_length() documentation. Otherwise, documentation is clear and well organized.

**Description of Functionality and Package Structure:**
Looks good – no concerns. 

**Overall review of package and fit in pharmaverse:**
Resolves a clear need. Well documented. Good fit.

Decent management of issues – 73 total, 50 closed. Not all open are labeled – how many are bugs?? A handful are >1y old – may be ok. There is one bug that is almost 1 year old. Looks like it’s being worked on. 
 
Open pull requests – are None seem critical to exclude from pharmaverse as-is.
