### ISSUE TITLE
[New package request]: ggsurvfit

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/pharmaverse#231]
- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

**Name and description of package**
*ggsurvfit*
Ease the creation of time-to-event (i.e. survival) endpoint figures. The modular functions create figures ready for publication. Each of the functions that add to or modify the figure are written as proper 'ggplot2' geoms or stat methods, allowing the functions from this package to be combined with any function or customization from 'ggplot2' and other 'ggplot2' extension packages.

The package also includes utilities for users following the CDISC ADaM model, with functions like `Surv_CNSR()` that transforms data in the ADaM format to that expected by the survival package (and most other R packages that perform survival analysis). The package also uses the PARAM/PARAMCD fields, when present, to improve default descriptions and error handling.

**Category of package**
ADaM, Analysis

**Repository**
[A link to the publicly available source code.](https://github.com/ddsjoberg/ggsurvfit)

**Package Maintainer**
Daniel Sjoberg (@ddsjoberg)

**Who is involved in developing/maintaining this package?**
Sjoberg D (PCCTC/MSK)
Baillie M (Novartis)
Haesendonckx S (Janssen)
Treis T (Helmholtz Munich)

**Considerations for pharmaverse inclusion**
The ggsurvfit package uses the permissive MIT license. The package includes CI/CD of the R CMD Checks via GitHub Actions and codecov.io. The package is regularly checked on the development version of R, the current release version, and the last three releases. Checks are performed on Windows, Mac, and Linux systems. The package has 100% code coverage and is available for installation from CRAN.

Each function includes a detailed help file, and the package also includes detailed vignettes/articles outlining various use cases.

**Overall fit in pharmaverse**
While the package is useful for anyone performing time-to-event, or survival analysis, the package was built with guardrails in place specifically for those using the ADaM/ADTTE data model. For example, the the `ADTTE$CNSR` variable is coded in the opposite way it is expected by the survival package, and we've created a function to handle the transformation, which is useful not only in the ggsurvfit package, but is also useful for any survival analysis in R. Moreover, the package detects the ADTTE structure and includes additional checks when users potentially specify the model incorrectly, e.g. if PARAM/PARAMCD are not unique within the data set and the results are not stratified by these columns, users will see a note about the likely mis-specification of the model.

There is another package available that has similar functionality to ggsurvfit---survminer. However, there is an unfortunate and unaddressed bug in the package that can unlink the legend to the colors of the estimates in the figure. The result being that the estimate of survival for Group A is labelled as Group B in the legend, and *vice versa*.

The development of ggsurvfit began in the visR package (another cross-pharma collaboration). In order to make big changes to the user interface without introducing massive breaking changes in visR, we spun the survival components of visR off into ggsurvfit.

**Comment by rossfarrugia** [comment]
@elimillera @MichaelRimler i originally was going to tag TLG WG but think this fits in ours for review.

**Comment by MichaelRimler** [comment]
**Description of Automated Tests/Checks:**
Code coverage is 100% - how does 'codecov' compare to 'Test Coverage' from other packages like admiral? If similar, then no concern. 

**Description of Package Documentation:**
CDISC ADaM ADTTE - would like this section to reference with ADaM IG versions are supported (or not supported) by ggsurvfit

Nice companion website.

**Description of Functionality and Package Structure:**
Looks good – no concerns.

**Overall review of package and fit in pharmaverse:**
Appears to resolve a clear reporting need that is not fully replicated elsewhere.
Package maintainers should connect with PHUSE/PSI CAMIS working group for user testing - how useful and robust are the features? [This is not a rate limiting request; it is a suggestion.]

Decent management of issues – many are created by developers directly. Recent closed issues appear to be submitted by a wider GH user base. 

Open pull requests – None seem critical to exclude from pharmaverse as-is.

**Comment by ddsjoberg** [comment]
Thank you @MichaelRimler for the review!

FYI I've made GH Issues for the points raised, and I'll make the updates with the next {ggsurvfit} release.
https://github.com/ddsjoberg/ggsurvfit/issues/151
https://github.com/ddsjoberg/ggsurvfit/issues/152

**Comment by rossfarrugia** [comment]
codecov is fine @MichaelRimler - no concerns.

Finally getting around to writing up my comments on this one:

- As this package is from the team behind visR it gives me a base level of confidence and I feel these are exactly the kind of cross-industry collaboratively built packages that pharmaverse should be helping to raise up. 
- Out of interest @ddsjoberg why is it hosted under github.com/ddsjoberg rather than a more neutral home like github.com/openpharma as with visR? I wonder if there's ever an adoption impact concern here, as some companies may make the quick assumption that this is only maintained/owned by one person and therefore more risky to incorporate into their GxP workflow. This won't impact you being approved for pharmaverse but just wanted to share it as a consideration.
- I see the gap that this fills and I also appreciate the efforts to tailor it towards ease of use in a CDISC clinical reporting dataflow, which again fits well with pharmaverse.
- The comparison against other similar existing packages helps to determine why this should standalone.
- The documentation seems great to me with lots of useful and realistic examples.
- No concerns with testing or level of support and maintenance.

Overall it's a yes from my side.

**Comment by rossfarrugia** [comment]
My only other thought is where this would live on pharmaverse site if we all accept it. Having reviewed it I would recommend putting it underneath visR at https://pharmaverse.org/e2eclinical/tlg/ - FYI @mstackhouse in case any concern as TLG WG Lead _(Note: we ended up reviewing this due to the overlap with ADaM but I feel like users would most likely find it on this page)_.

**Comment by elimillera** [comment]
For Each Review
Description of Automated Tests/Checks:
Test coverage is at 100% and package tests seem to be robust and have solid depth and utilize snapshot testing.

Description of Package Documentation:
Function and package documentation is thorough. Vignettes and examples are available.

Description of Functionality and Package Structure:
Clear functionality and standard package structure

Overall review of package and fit in pharmaverse:
Seems to close an existing gap. A review of the field by the package authors note the need this meets.

**Comment by ddsjoberg** [comment]
Thank you @rossfarrugia and @elimillera !

- @rossfarrugia the pkg started as a sandbox for implementing new features in visR. But the changes we wanted to make to the API was too big to be incorporated into visR, so the new package emerged from my personal GH account. I am happy to transfer it to the pharmaverse if you're amenable. Since the package has been around for a year now and gets pretty widely used (5000+ downloads/month), I'll likely keep the website hosted where it currently lives, as to not break links and diminish the current SEO.
- The visR pkg is listed twice on the pharmaverse website: once in "End-to-End Clinical Reporting Packages" (where @rossfarrugia suggested to add ggsurvfit), and once in "Other Useful Packages" (where @elimillera linked to). I feel it belongs more in the End-to-End section.

**Comment by rossfarrugia** [comment]
Hi @ddsjoberg, we'd be open to that. I think moving to pharmaverse org could help with companies adopting. We did similar in the past with admiral where originally it was under a "Roche-GSK" org and again we felt this could have negative repercussions to adoption and the ability to bring in further collaborators from other companies, so we moved it to the more neutral pharmaverse org. I'll wait for the transfer before posting to our site so that I don't need to change the GH repo link. Absolutely fine for the site too, I remember the pain of all the broken links 😆 

Also as part of the update to the site to add ggsurvfit, happy to remove visR from the Other page to clean this up.

**Comment by rossfarrugia** [comment]
> Looks good to go from the Data WG. Package to be placed in the graphs section: https://pharmaverse.org/nonpharma/

Think this was a typo Eli... we discussed adding to this page: https://pharmaverse.org/e2eclinical/tlg/

**Comment by ddsjoberg** [comment]
@rossfarrugia great! I'll do a bit of investigating to get my GH actions to pull the repo from pharmaverse, and deploy the website to it's current location.

I've got a pretty hairy week, but think I should have this all figured out within 2 weeks.

**Comment by ddsjoberg** [comment]
Hey hey @rossfarrugia ! I figured out the GH Actions for website deployment 🍾 

We can transfer the repo anytime now. How do you want to go about making the transfer? What do I need to do from my end?

**Comment by rossfarrugia** [comment]
👍  Will drop you a mail and we can sort this transfer together.

**Comment by ddsjoberg** [comment]
Thank you @rossfarrugia @elimillera @MichaelRimler for the review of the ggsurvfit package! It has now been transferred to the pharmaverse org! 
https://github.com/pharmaverse/ggsurvfit

Can one of the org owners grant me admin/owner rights to the repo? I need to clean up a few references now that the transfer is complete, and my repo rights didn't transfer over.

**Comment by rossfarrugia** [comment]
Thanks @ddsjoberg - you're now an admin again. I'll get the package added to the pharmaverse site soon.
