### ISSUE TITLE
DataWG: {Package Review}: sdtmchecks

### ISSUE THREAD

**Issue by elimillera** [pharmaverse/pharmaverse#232]
**Name and description of package**
 Functions to identify common data issues in SDTM data. These checks are intended to be generalizable, actionable, and meaningful for analysis. 

**Category of package**
SDTM

**Repository**
https://github.com/pharmaverse/sdtmchecks

**Package Maintainer**
@harriscw

**Who is involved in developing/maintaining this package?**
Roche/Genentech, @rossfarrugia, @sarabodach, @fernank8

**Considerations for pharmaverse inclusion**
Describe license type, automated tests/checks, and package documentation.

**Overall fit in pharmaverse**
Why you believe this should belong in the pharmaverse? Please call out any novel or duplicative functionality relative to the existing pharmaverse packages.

Reviewers: @elimillera @MichaelRimler

**Comment by AxelMuehlig** [comment]
This seems to be a useful package, complementing edit checks. 
One question: How robust are the currently available checks towards future SDTM IG versions? And how would backward compatibility be addressed if new IG's require modifications of individual checks?

**Comment by MichaelRimler** [comment]
**Description of Automated Tests/Checks:**
No information provided (that I see) - we need this information to be built in.
Would also like to see similar badges as otehr packages - passing RCMD checks?
Is this on CRAN?

**Description of Package Documentation:**
Companion website is difficult to read. Suggest improving readability (I am viewing in Chrome).

Also suggest to improve the organization and content of the companion website. Would like to see a high-level characterization of the scope of checks - perhaps grouped by some categories? Something that is user friendly and digestible. When I review the 'Reference' page, it is not easy for me (as a user) to understand if sdtmchecks would address a specific issue. 

Similar to other 'CDISC' related packages - suggest that a reference to which SDTM IG versions are supported by this package. This information is critical for the user base to understand.

**Description of Functionality and Package Structure:**
Looks good – no concerns, as I understand. I have no concern on the content of the package - let the users submit issues if there are gaps. However, the supporting documentation could use some improvement to make it easier for the user to understand and browse.

**Overall review of package and fit in pharmaverse:**
Resolves a clear gap in the R space (in my opinion). I'd like to see the documentation rise to the level expected to support pharmaverse users. Pharamaverse exists to lessen the burden of the more novice R programmer to evaluate what solutions are available for them to use for their current problem.

Decent management of issues – but many are created by developers directly. Are we confident that support will continue - or is there a 'probation period' that is needed? 

Open pull requests – None seem critical to exclude from pharmaverse as-is.

**Comment by rossfarrugia** [comment]
Hi all, I'm not on the review of this one given I internally sponsor the package at Roche, but just wanted to call out for transparency that when I reviewed it before one of my initial concerns was there's no unit tests, but then when I thought about the scope and purpose of the package in the remit of clinical reporting I was OK with this. As it's more like an informal utility check program, rather than anything directly contributing to a GxP pipeline.

Thanks for the useful comments above so far! Happy to discuss these with the dev team once we finish the review. A few quick replies for now:
- not on CRAN - could check if this is ever planned
- for the characterisation of functions I think they'd probably comment that this is covered in their naming convention, e.g. "check_**ae**_xxx", "check_**ds**_xxx" etc but let's see what they think
- i'm confident support will continue for this one as it's used almost universally by all teams at Roche right now - also this gives confidence in the compatibility across different SDTM versions as we have all sorts of old and new studies using this. It is an area that needs to be monitored and maintained for though

**Comment by elimillera** [comment]
For Each Review
Description of Automated Tests/Checks:
No automated checks exist for this package 
main is currently ahead of devel in commits

Description of Package Documentation:
README is light on use cases and use of package
Getting started is heavy on Headers

Description of Functionality and Package Structure:
The structure of one test per file may result in a large R/ directory. It may be advisable to standardize function documentation as well. Roxygen includes standard function families which can help documentation stay up to date and consistent.

Overall review of package and fit in pharmaverse:
The package use case itself is a great effort and a welcome step forward into open source dataset checks.
However, no testing or CI exists for the packages, this is a requirement for pharmaverse inclusion[https://pharmaverse.org/contribute/lead/]
It is also recommended that package documentation be expanded.

**Comment by rossfarrugia** [comment]
Thanks @sarabodach for the update - all sounds good! I would recommend to advertise this release on the sdtmchecks Slack channel, as I think it will help attract new users.

I'll close this issue now as resolved but anyone from the Data WG can re-open if they see any further comments.
