### ISSUE TITLE
Check: riskmetric still maintained?

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#277]
@AARON-CLARK @dgkf is riskmetric still maintained? Or is the R Validation Hub plan to move everything into riskassessment and only support this?

We heard feedback that riskmetric current version fails to run due to bugs. Let us know the plan so we know whether to remove riskmetric from pharmaverse site. If it is still being maintained then the reporter offered some contributions so we could link you.

**Comment by AARON-CLARK** [comment]
Hi @rossfarrugia!

Yes, `{riskmetric}` is still being actively developed. Just to clarify, do they mean R CMD Check fails or something else? I can't speak to any current "version fails" but maybe @elimillera  or @emilliman5 can comment since they're responsible for CRAN releases and dev progress respectively. Please link them for any bug fixes.

I do know that the `{riskmetric}` version (v0.2.3) being used in the `{riskassessment}` app's `renv.lock` [file](https://github.com/pharmaR/riskassessment/blob/dev/renv.lock#L2307) has been stable. I do know that there are a couple known bugs they are working on, including some superficial [CRAN failures](https://github.com/pharmaR/riskmetric/issues/324) that were fixed Dec 20th.

Just glancing at the repo, it looks like `master` is on [v0.2.4](https://github.com/pharmaR/riskmetric/blob/master/DESCRIPTION#L6) and [so is CRAN](https://cran.r-project.org/web/packages/riskmetric/index.html). I didn't see any open GitHub issues regarding failures so I'd encourage the reporter to start by opening one up.

**Comment by dgkf** [comment]
Just to add to what Aaron already said, riskmetric and riskassessment are
complementary, not redundant.

riskassessment leverages riskmetric under the hood for (most) metrics, and
when new ones are introduced the goal is that they make their way back into
riskmetric.

You can think of them more as being interfaces to the same tooling - a
scripting tool for developers/administrators and a graphical tool for
non-technical users. If you're hitting bugs while using one or the other,
please continue to report them! We intend to continue supporting both!

-Doug

**Comment by rossfarrugia** [comment]
Good to hear - let me connect you guys by mail and hopefully this leads to some more contributions for you!
